### PR TITLE
Added random length

### PR DESCRIPTION
**Pull request by erusso7**
I don't need 16 chars of random per second, I would like to customize the length and this is close to modification from outside.

### CODE REVIEW

**Comment by Lewiscowles1986** [comment]
Unfortunately I don't believe this benefits the library.

**Comment by erusso7** [comment]
Oh! :(
So... Why the methods encodeTme and encodeRandom have a parameter length, if it's fixed? 
This should be a constant, maybe?

**Comment by sergiq** [comment]
Jeezz... @Lewiscowles1986  let the code be more consistent and start using the same convention for the same package (We are not in the 80's).

**Comment by Lewiscowles1986** [comment]
Thank you both for your input, but this is getting locked. Learn how to behave and put forward your ideas.

**Pull request closed without merging**
