### PR TITLE
Assertion readability

### PR DESCRIPTION
**Pull request by peter279k**
# Changed log

- replace the ```assertTrue``` with ```assertGreaterThan``` and ```assertLessThan``` and it can make us read the assertion easily.

### CODE REVIEW

**Comment by Lewiscowles1986** [comment]
I think we have a slight difference of opinion here.

Whilst a message would probably make the test fail in a nicer way to say random is out of range, I'm not sure splitting into two assertions is going to help that. If it were split into two test-cases (one for each), that would be fine and dandy.

**Comment by peter279k** [comment]
How about splitting two tests which are named ```testRandIsGreaterThan0``` and ```testRandIsLessThan1```?

I think it will be failed if the result value is out of range in that two assertions.

**Comment by Lewiscowles1986** [comment]
Hi Peter,

Three final pieces of feedback pre-merge.

Please roll up commits, or (better) split branch on unrelated commits.
Please remove the test case being removed (git will take care of preserving history :wink:)
Please sign commits 

```
git commit -s -m "message" -m "longer 
body 
message
"

```

really appreciate the input :+1:

**Comment by Lewiscowles1986** [comment]
Edited above: Please remove the test case being removed (git will take care of preserving history wink)

**Comment by peter279k** [comment]
I think the roll up commit work should be done by yourself.
You can check out this [guide](https://help.github.com/articles/merging-a-pull-request/) to konw about squash all commits into one commit when mergring the PR :-).

**Comment by Lewiscowles1986** [comment]
Hi Peter,

They are pretty common rules for contributing. I know how to roll up commits, but it's not the only issue I've raised. Can I ask what the problem is with any of the above three?

**Comment by peter279k** [comment]
- The rolling up commits I think it can be squashed when merging the PR.
- Which test cases should be removed?
- It' the same explanation in first item.

**Comment by Lewiscowles1986** [comment]
Really sorry then @peter279k but I can't merge this. Whilst I do appreciate the enthusiasm none of these address existing tickets, and your unwillingness to participate probably means your changes should live in your branch.

Thank you for your suggestions though.

**Pull request closed without merging**
